- name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@v0.7.1
        with:
          local: test
          remote: scp/directory
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
